# Generated by Django 5.2.12 on 2026-03-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_productcategoryhierarchy_category_exclude_from_menu_and_more'),
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('cmsplugins', '0004_adacollabproduct_groupbuyproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftsProduct',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
